name: Continuous deployement

on:
  pull_request:
    branches: ["master"]

jobs:
  deploy_to_firebase:
    runs-on: [windows-latest,self-hosted]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'

      # Install Firebase CLI
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # Run tests
      - name: Run tests
        run: npm ci
        run: npm test
      - run: npm run build

      - uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

    
