name: Continuous integration

on:
  pull_request:
    branches: ["master"]

jobs:
  pr_test:
    runs-on: [windows-latest,self-hosted]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'

      # Install Firebase CLI
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # Run tests
      - run: npm ci
  

